apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1xvx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1xvx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1xvx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1xvx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1xvx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ovdn-tenant/rhtap-demo-app/hacbs-test-project-1xvx@sha256:d50a1b388737ca7c366426b2418a8552762723676f69b240e25666619a8a115f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
